### PR TITLE
Adding the python3-ruamel-yaml package to Dockerfile.

### PR DESCRIPTION
**Pull request by nhosoi**
Details are found in this comment.
https://github.com/linux-system-roles/test-harness/issues/115#issuecomment-723287239

### CODE REVIEW

**Comment by nhosoi** [comment]
@richm, @pcahyna, @jharuda, could you please review? Thanks in advance.

**Review by jharuda — COMMENTED** [review]
lgtm

**Review by jharuda — APPROVED** [review]

**Comment by nhosoi** [comment]
Thank you for your review, @jharuda! Since I have no write access, could you please merge this PR? Thanks!!

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
