### PR TITLE
Container: Use dumb-init to avoid zombie processes

### PR DESCRIPTION
**Pull request by tyll**
References: https://github.com/Yelp/dumb-init

FYI: I did not test it locally, yet.

### CODE REVIEW

**Comment by tyll** [comment]
@yontalcar awesome, thank you very much!

I forgot about the staging branch - should I file a PR to merge it there first?

**Comment by yontalcar** [comment]
@tyll I don't think it is needed, it doesn't have any active deployments now anyway

**Comment by tyll** [comment]
@yontalcar ok, thank you. Will you deploy the change or should I do it?

**Comment by yontalcar** [comment]
@tyll I'll deploy it

**Pull request merged**
