### PR TITLE
RHELPLAN-59406 - Disable the collection tests for centos-7 in deploymentconfig

### PR DESCRIPTION
**Pull request by nhosoi**
openshift-playbook.yml - Adding "| combine(test_harness_deploy_env_centos7)"
    to __test_harness_deploy_env for staging and production centos7 to override
    TEST_HARNESS_COLLECTIONS with false.

Note: This PR depends on https://gitlab.cee.redhat.com/rhel-system-roles/test-harness-config/-/merge_requests/73

### CODE REVIEW

**Comment by nhosoi** [comment]
@richm, @jharuda, @pcahyna, could you please take a look?

**Comment by jharuda** [comment]
LGTM

**Review by jharuda — APPROVED** [review]

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
Thank you for reviewing this PR, @jharuda and @richm.
Since https://gitlab.cee.redhat.com/rhel-system-roles/test-harness-config/-/merge_requests/73 is merged, this PR is safe to merge. Could you please do so as I don't have the permission.

**Pull request merged**
